version: '3'
services:

  mwae_client:
    container_name: mwae_client_container
    build:
      context: ./client
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - ./client/workdir:/workdir
      - ./volumes/data:/data
    ports:
      - "21030:3000"
    command: /bin/sh -c "while true; do echo faking deamon; sleep 60; done"

  mwae_db:
    container_name: mwae_db_container
    image: postgres

  mwae_core:
    container_name: mwae_core_container
    build:
      context: ./core
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./core/workdir:/workdir
      - ./volumes/data:/data
    ports:
      - "21080:8000"
    command: /bin/sh -c "while true; do echo faking deamon; sleep 60; done"
    depends_on:
      - mwae_db

  mwae_go_github_service:
    container_name: mwae_go_github_service_container
    build:
      context: ./github-service
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./github-service/workdir:/workdir
    ports:
      - "21090:8080"
    command: /bin/sh -c "while true; do echo faking deamon; sleep 60; done"
