version: '3'
services:

  client:
    container_name: mwae_client
    build:
      context: ./client
      dockerfile: ./docker/nodejs/Dockerfile
    volumes:
      - ./client/workdir:/workdir
      - ./volumes/data:/data
    ports:
      - "21030:3000"
    command: ./run.sh

  db:
    container_name: mwae_db
    build:
      context: ./core
      dockerfile: ./docker/postgresql/Dockerfile
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/backup:/backup
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "Passw0rd33"

  rabbitmq:
    container_name: mwae_rabbitmq
    image: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: "rbmq_user"
      RABBITMQ_DEFAULT_PASS: "Passw0rd33"

  core:
    container_name: mwae_core
    build:
      context: ./core
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./core/workdir:/workdir
      - ./volumes/data:/data
    ports:
      - "21080:8000"
    command: ./run.sh
    depends_on:
      - db
      - rabbitmq

  celery_worker:
    container_name: mwae_celery_worker
    build:
      context: ./core
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./core/workdir:/workdir
    command: celery -A app worker -l info
    depends_on:
      - db
      - core
      - rabbitmq

  celery_beat:
    container_name: mwae_celery_beat
    build:
      context: ./core
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./core/workdir:/workdir
    command: celery -A app beat -l info
    depends_on:
      - db
      - core
      - rabbitmq
      - celery_worker

  flower:
    container_name: mwae_flower
    build:
      context: ./core
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - ./core/workdir:/workdir
    command: celery flower -A app --address=0.0.0.0 --port=5555
    depends_on:
      - db
      - core
      - rabbitmq
      - celery_worker
    ports:
      - "5555:5555"

  go_github_service:
    container_name: mwae_go_github_service
    build:
      context: ./services/github
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./services/github/workdir:/workdir
    ports:
      - "21090:8080"
    command: ./run.sh
